# Use Java 22 base image
FROM eclipse-temurin:22-jdk-alpine

# Set working directory inside container
WORKDIR /app

# Copy Maven Wrapper and pom.xml files first (for caching)
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

# Download dependencies (this speeds up builds)
RUN ./mvnw dependency:go-offline

# Copy all project files
COPY . .

# Build the project (skip tests for faster build)
RUN ./mvnw clean package -DskipTests

# Expose the port your Spring Boot app runs on
EXPOSE 8080

# Run the Spring Boot app
CMD ["java", "-jar", "target/Url_Shortener-0.0.1-SNAPSHOT.jar"]
